# Generated by Django 4.0.4 on 2022-05-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_super_super_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='super_type',
        ),
    ]
